import { FeatureDefinitionSchema, type FeatureDefinition } from "../schemas.ts";
import { contentHash } from "../hash.ts";

type Draft = Omit<FeatureDefinition, "id"> & { expression: string };

function def(d: Draft): FeatureDefinition & { expression: string; formulaHash: string } {
  const formulaHash = contentHash({
    expression: d.expression,
    lookback: d.lookback,
    timeframe: d.timeframe,
    family: d.family,
  });
  const parsed = FeatureDefinitionSchema.parse({
    ...d,
    id: `feat_${contentHash({ name: d.name, version: d.version }).slice(0, 16)}`,
  });
  return { ...parsed, expression: d.expression, formulaHash };
}

const drafts: Draft[] = [
  {
    name: "ret_1d",
    definition: "Close-to-close simple return. Bar-close only.",
    parameters: { window: 1 },
    lookback: 1,
    timeframe: "1d",
    availabilityRule: "bar_close",
    units: "1",
    family: "price",
    version: "1",
    sourceDependencies: ["bar.close"],
    coordinateAxisId: "ax_ret",
    expression: "(c[t]-c[t-1])/c[t-1]",
  },
  {
    name: "log_close",
    definition: "Natural log of close.",
    parameters: {},
    lookback: 0,
    timeframe: "1d",
    availabilityRule: "bar_close",
    units: "log USD",
    family: "price",
    version: "1",
    sourceDependencies: ["bar.close"],
    coordinateAxisId: "ax_px",
    expression: "log(c[t])",
  },
  {
    name: "sma_20",
    definition: "20-session simple moving average of close.",
    parameters: { window: 20 },
    lookback: 19,
    timeframe: "1d",
    availabilityRule: "bar_close",
    units: "USD",
    family: "trend",
    version: "1",
    sourceDependencies: ["bar.close"],
    coordinateAxisId: "ax_px",
    expression: "mean(c[t-19..t])",
  },
  {
    name: "sma_20_alias",
    definition: "Duplicate of sma_20 for formula-collision audit.",
    parameters: { window: 20 },
    lookback: 19,
    timeframe: "1d",
    availabilityRule: "bar_close",
    units: "USD",
    family: "trend",
    version: "1",
    sourceDependencies: ["bar.close"],
    coordinateAxisId: "ax_px",
    expression: "mean(c[t-19..t])",
  },
  {
    name: "rsi_14",
    definition: "Wilder RSI(14) on close. Coordinate, not a claim.",
    parameters: { window: 14 },
    lookback: 14,
    timeframe: "1d",
    availabilityRule: "bar_close",
    units: "0-100",
    family: "momentum",
    version: "1",
    sourceDependencies: ["bar.close"],
    coordinateAxisId: "ax_rsi",
    expression: "wilder_rsi(c,14)",
  },
  {
    name: "atr_14",
    definition: "Average true range(14).",
    parameters: { window: 14 },
    lookback: 14,
    timeframe: "1d",
    availabilityRule: "bar_close",
    units: "USD",
    family: "range_volatility",
    version: "1",
    sourceDependencies: ["bar.high", "bar.low", "bar.close"],
    coordinateAxisId: "ax_atr",
    expression: "mean(true_range[t-13..t])",
  },
  {
    name: "rv_20",
    definition: "20-session realized vol of 1d log returns, annualized √252.",
    parameters: { window: 20 },
    lookback: 20,
    timeframe: "1d",
    availabilityRule: "bar_close",
    units: "1/sqrt(year)",
    family: "range_volatility",
    version: "1",
    sourceDependencies: ["bar.close"],
    coordinateAxisId: "ax_vol",
    expression: "sqrt(252)*std(logret[t-19..t])",
  },
  {
    name: "vol_z_20",
    definition: "Volume z-score vs 20-session mean/stdev.",
    parameters: { window: 20 },
    lookback: 19,
    timeframe: "1d",
    availabilityRule: "bar_close",
    units: "1",
    family: "volume",
    version: "1",
    sourceDependencies: ["bar.volume"],
    coordinateAxisId: "ax_volm",
    expression: "(v[t]-mean(v))/std(v)",
  },
  {
    name: "hl_range",
    definition: "Intraday high-low over close. Proxy, not true microstructure.",
    parameters: {},
    lookback: 0,
    timeframe: "1d",
    availabilityRule: "bar_close",
    units: "1",
    family: "microstructure",
    version: "1",
    sourceDependencies: ["bar.high", "bar.low", "bar.close"],
    coordinateAxisId: "ax_hl",
    expression: "(h[t]-l[t])/c[t]",
  },
  {
    name: "atm_iv",
    definition: "ATM IV from a surface event if present at T; else missing.",
    parameters: {},
    lookback: 0,
    timeframe: "1d",
    availabilityRule: "surface.available",
    units: "1",
    family: "volatility_surface",
    version: "1",
    sourceDependencies: ["surface.atm_iv"],
    coordinateAxisId: "ax_iv",
    expression: "surface.atm_iv",
  },
  {
    name: "net_delta",
    definition: "Position net delta if a mark is supplied; else missing.",
    parameters: {},
    lookback: 0,
    timeframe: "1d",
    availabilityRule: "position.mark",
    units: "shares",
    family: "options_exposure",
    version: "1",
    sourceDependencies: ["position.delta"],
    coordinateAxisId: "ax_delta",
    expression: "sum(q*multiplier*delta)",
  },
  {
    name: "days_to_catalyst",
    definition: "Sessions until next catalyst with availability_time <= T and event_time >= T.",
    parameters: {},
    lookback: 0,
    timeframe: "1d",
    availabilityRule: "catalyst.available",
    units: "sessions",
    family: "catalyst",
    version: "1",
    sourceDependencies: ["catalyst.scheduled"],
    coordinateAxisId: "ax_cal",
    expression: "min(event_time>=T | avail<=T)",
  },
  {
    name: "dow",
    definition: "UTC day-of-week of the session (1=Mon..5=Fri).",
    parameters: {},
    lookback: 0,
    timeframe: "1d",
    availabilityRule: "session",
    units: "dow",
    family: "calendar",
    version: "1",
    sourceDependencies: ["calendar"],
    coordinateAxisId: "ax_cal",
    expression: "utc_dow(session)",
  },
  {
    name: "weekly_ret",
    definition: "Friday-to-Friday return. Available only at/after that Friday close.",
    parameters: {},
    lookback: 5,
    timeframe: "1w",
    availabilityRule: "week_close",
    units: "1",
    family: "price",
    version: "1",
    sourceDependencies: ["bar.close"],
    coordinateAxisId: "ax_ret",
    expression: "(fri_close-prev_fri_close)/prev_fri_close",
  },
  {
    name: "strategy_age",
    definition: "Sessions since last strategy-state change, if provided.",
    parameters: {},
    lookback: 0,
    timeframe: "1d",
    availabilityRule: "strategy.available",
    units: "sessions",
    family: "strategy",
    version: "1",
    sourceDependencies: ["strategy.state"],
    coordinateAxisId: "ax_strat",
    expression: "t - last_transition",
  },
];

export const FEATURE_CATALOG = drafts.map(def);

export function catalogByName(name: string) {
  const f = FEATURE_CATALOG.find((x) => x.name === name);
  if (!f) throw new Error(`UNKNOWN_FEATURE: ${name}`);
  return f;
}

export function requiredFamilies(): string[] {
  return [...new Set(FEATURE_CATALOG.map((f) => f.family))];
}
