/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EssnRouteImport } from './routes/essn'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as GatesRouteImport } from './routes/gates'
import { Route as GeometryRouteImport } from './routes/geometry'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RuntimeRouteImport } from './routes/runtime'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EssnRoute = EssnRouteImport.update({
  id: '/essn',
  path: '/essn',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesRoute = GatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const GeometryRoute = GeometryRouteImport.update({
  id: '/geometry',
  path: '/geometry',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeRoute = RuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/essn': typeof EssnRoute
  '/evidence': typeof EvidenceRoute
  '/gates': typeof GatesRoute
  '/geometry': typeof GeometryRoute
  '/login': typeof LoginRoute
  '/runtime': typeof RuntimeRoute
  '/strategy': typeof StrategyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/essn': typeof EssnRoute
  '/evidence': typeof EvidenceRoute
  '/gates': typeof GatesRoute
  '/geometry': typeof GeometryRoute
  '/login': typeof LoginRoute
  '/runtime': typeof RuntimeRoute
  '/strategy': typeof StrategyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/essn': typeof EssnRoute
  '/evidence': typeof EvidenceRoute
  '/gates': typeof GatesRoute
  '/geometry': typeof GeometryRoute
  '/login': typeof LoginRoute
  '/runtime': typeof RuntimeRoute
  '/strategy': typeof StrategyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/essn'
    | '/evidence'
    | '/gates'
    | '/geometry'
    | '/login'
    | '/runtime'
    | '/strategy'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/essn'
    | '/evidence'
    | '/gates'
    | '/geometry'
    | '/login'
    | '/runtime'
    | '/strategy'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/essn'
    | '/evidence'
    | '/gates'
    | '/geometry'
    | '/login'
    | '/runtime'
    | '/strategy'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EssnRoute: typeof EssnRoute
  EvidenceRoute: typeof EvidenceRoute
  GatesRoute: typeof GatesRoute
  GeometryRoute: typeof GeometryRoute
  LoginRoute: typeof LoginRoute
  RuntimeRoute: typeof RuntimeRoute
  StrategyRoute: typeof StrategyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essn': {
      id: '/essn'
      path: '/essn'
      fullPath: '/essn'
      preLoaderRoute: typeof EssnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates': {
      id: '/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof GatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geometry': {
      id: '/geometry'
      path: '/geometry'
      fullPath: '/geometry'
      preLoaderRoute: typeof GeometryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime': {
      id: '/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof RuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EssnRoute: EssnRoute,
  EvidenceRoute: EvidenceRoute,
  GatesRoute: GatesRoute,
  GeometryRoute: GeometryRoute,
  LoginRoute: LoginRoute,
  RuntimeRoute: RuntimeRoute,
  StrategyRoute: StrategyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
